image: dashori/golang-dind:1.21.3

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - test
  - report
    
unit-tests:
    stage: test
    script:
      - cd backend/internal/services/implementation
      - go test pet_test.go client_test.go doctor_test.go record_test.go pet.go record.go client.go doctor.go setup.go -gcflags=all=-l -tags=unit -cover -coverprofile=serviceTest.out -json -v > testService.log
      - cd -
      - cd backend/internal/repository/postgres_repo
      - go test -gcflags=all=-l -tags=unit -cover -coverprofile=serviceTest.out -json ./... -v > testRepos.log   
      - echo "all is ok"
    artifacts:
      paths:
        - backend/internal/services/implementation/testService.log
        - backend/internal/repository/postgres_repo/testRepos.log

int-tests:
    stage: test
    script:
      - cd backend/internal/services/implementation 
      - go test petPostgres_test.go recordPostgres_test.go pet.go record.go setup.go  -gcflags=all=-l -tags=integration -cover -coverprofile=serviceIntegration.out -json -v > testIntegration.log  
      - echo "all is ok"
    needs:
      - unit-tests
    artifacts:
      paths:
        - backend/internal/services/implementation/testIntegration.log

e2e-tests:
  stage: test
  script:
    - docker-compose up -d
    - docker ps
    - cd e2e
    - go run main.go
    - docker-compose down
  needs:
    - int-tests

report:
    stage: report
    dependencies:
      - unit-tests
      - int-tests
    script:
      - go install github.com/polnaya-katuxa/test-report@latest
      - mv backend/internal/services/implementation/testService.log testService.log
      - mv  backend/internal/repository/postgres_repo/testRepos.log testRepos.log
      - mv backend/internal/services/implementation/testIntegration.log testIntegration.log
      - touch test.log
      - cat testService.log >> test.log
      - cat testRepos.log >> test.log
      - cat testIntegration.log >> test.log
      - test-report -f ./test.log -o .
    artifacts:
      paths:
        - report.html
# backend-module-build-job:      
#   stage: pre
#   when: always
#   script:
#       - cd backend 
#       - go mod init backend
#       - go mod tidy
#   artifacts:
#     paths:
#       - backend/go.sum
#       - backend/go.mod
#     expire_in: 1 hour
  
  
# linter-backend-job:
#   stage: pre
#   allow_failure: true
#   image: golangci/golangci-lint:v1.52.2
#   script:
#     - cd backend
#     - go mod tidy
#     - golangci-lint run --timeout 3m0s
#   needs:
#     - backend-module-build-job


# console-module-build-job:      
#   stage: pre 
#   when: always
#   script:
#       - cd consoleApp 
#       - go mod init consoleApp
#       - go mod tidy
#   artifacts:
#     paths:
#       - consoleApp/go.sum
#       - consoleApp/go.mod
#     expire_in: 1 hour

# linter-console-job:
#   stage: pre
#   allow_failure: true
#   image: golangci/golangci-lint:v1.52.2
#   script:
#     - cd consoleApp
#     - go mod tidy
#     - golangci-lint run --timeout 3m0s
#   needs:
#     - console-module-build-job


# bl-unit-test-job:  
#   stage: test   
#   when: always
#   script:
#     - cd backend 
#     - go mod tidy
#     - cd internal/services/implementation
#     - go test client_test.go client.go -v -cover -coverprofile=client.out
#     - go test record.go record_test.go -v -cover -coverprofile=record.out
#     - go test pet_test.go pet.go -v -cover -coverprofile=pet.out
#     - go test doctor.go doctor_test.go -v -cover  -coverprofile=doctor.out
#   artifacts:
#     paths:
#       - backend/internal/services/implementation/client.out
#       - backend/internal/services/implementation/record.out
#       - backend/internal/services/implementation/pet.out
#       - backend/internal/services/implementation/doctor.out
#     expire_in: 1 hour
#   needs:
#     - backend-module-build-job
#     - linter-backend-job

# db-unit-test-job:  
#   stage: test   
#   when: always
#   script:
#     - cd backend 
#     - go mod tidy
#     - cd internal/services/implementation
#     - go test -v -cover -coverprofile=DB.out
#   artifacts:
#     paths:
#       - backend/internal/services/implementation/unitDB.out
#     expire_in: 1 hour
#   needs:
#     - backend-module-build-job
#     - linter-backend-job


# bl-db-test-job:  
#   stage: test  
#   when: always
#   script:
#     - cd backend 
#     - go mod tidy
#     - cd internal/services/implementation
#     - go test recordPostgres_test.go record.go record_test.go petPostgres_test.go pet.go pet_test.go setup.go -v -cover -coverprofile=DBDL.out
#   artifacts:
#     paths:
#       - backend/internal/services/implementation/DBDL.out
#     expire_in: 1 hour
#   needs:
#     - backend-module-build-job
#     - bl-unit-test-job
#     - db-unit-test-job


# backend-build-job:    
#   stage: build
#   when: always
#   script:
#     - cd backend 
#     - go mod tidy
#     - cd cmd
#     - go build main.go
#   artifacts:
#     paths:
#       - backend/cmd/main
#     expire_in: 1 hour
#   needs:
#     - backend-module-build-job
#     - bl-unit-test-job
#     - db-unit-test-job
#     - bl-db-test-job

# console-build-job:    
#   stage: build
#   when: always
#   script:
#     - cd consoleApp 
#     - go mod tidy
#     - go build main.go
#   artifacts:
#     paths:
#       - consoleApp/main
#     expire_in: 1 hour
#   needs:
#     - console-module-build-job
#     - linter-console-job
   

# research-job:   
#   stage: research  
#   script:
#     - cd backend 
#     - go mod tidy
#     - cd research
#     - go run *.go
#   artifacts:
#     paths:
#       - backend/research/result.txt
#     expire_in: 4 hour
#   when: always
#   needs:
#    - backend-module-build-job

# result-research-graph:
#   stage: research  
#   image: python
#   before_script:
#     - pip install matplotlib
#   script:
#     - cd backend/research
#     - python3 main.py
#     - python3 errors.py
#   artifacts:
#     paths:
#       - backend/research/resultGraph.png
#       - backend/research/resultError.png
#     expire_in: 4 hour
#   when: always
#   needs:
#    - research-job

