image: dashori/golang-dind:1.21.3

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - test
  - report
    
# vault-test:
#   stage: test
#   script:
#     - echo $CI_COMMIT_REF_NAME
#     - echo $CI_COMMIT_REF_PROTECTED
#     - echo $CI_JOB_JWT
#     - export VAULT_ADDR='http://127.0.0.1:8200'
#     - export PASSWORD="$(vault kv get -field=password secret/emailFrom)"
#     - echo $PASSWORD
#     - export PASSWORD="$(vault kv get -field=password secret/emailTo)"
#     - echo $PASSWORD

#   tags:
#     - shell

unit-tests:
  stage: test
  script:
    - touch backend/internal/services/implementation/testRepos.log 
    - touch backend/internal/repository/postgres_repo/testRepos.log
    - cd backend/internal/services/implementation
    - go test pet_test.go client_test.go doctor_test.go record_test.go pet.go record.go client.go doctor.go setup.go -gcflags=all=-l -tags=unit -cover -coverprofile=serviceTest.out -json -v > testService.log
    - cd -
    - cd backend/internal/repository/postgres_repo
    - go test -gcflags=all=-l -tags=unit -cover -coverprofile=serviceTest.out -json ./... -v > testRepos.log   
    - echo "all is ok"
  artifacts:
    paths:
      - backend/internal/services/implementation/testService.log
      - backend/internal/repository/postgres_repo/testRepos.log

int-tests:
  stage: test
  script:
    - touch backend/internal/services/implementation/testIntegration.log
    - cd backend/internal/services/implementation 
    - go test petPostgres_test.go recordPostgres_test.go pet.go record.go setup.go  -gcflags=all=-l -tags=integration -cover -coverprofile=serviceIntegration.out -json -v > testIntegration.log  
    - echo "all is ok"
  dependencies:
    - unit-tests
  artifacts:
    paths:
      - backend/internal/services/implementation/testIntegration.log

e2e-tests:
  stage: test
  script:
    - export VAULT_ADDR='http://127.0.0.1:8200'
    - export PASSWORD_FROM="$(vault kv get -field=password secret/emailFrom)"
    - export PASSWORD_TO="$(vault kv get -field=password secret/emailTo)"
    - echo $PASSWORD_FROM
    - echo $PASSWORD_TO
    - docker-compose up -d
    - docker ps
    - cd e2e
    - go run main.go
    - docker-compose down
  dependencies:
    - int-tests
  tags:
    - shell

report:
    stage: report
    needs:
      - unit-tests
      - int-tests
    script:
      - go install github.com/polnaya-katuxa/test-report@latest
      - mv backend/internal/services/implementation/testService.log testService.log
      - mv backend/internal/repository/postgres_repo/testRepos.log testRepos.log
      - mv backend/internal/services/implementation/testIntegration.log testIntegration.log
      - touch test.log
      - cat testService.log >> test.log
      - cat testRepos.log >> test.log
      - cat testIntegration.log >> test.log
      - test-report -f ./test.log -o .
    artifacts:
      paths:
        - report.html